version: "3.1"

services:
  opencart:
    build:
      context: docker
      dockerfile: Dockerfile.dev
      args:
        EXTENSION_PATH:
        OPENCART_VERSION:
        APP_PORT:
        DOCKER_USER:
        OPENCART_PATH:
        OPENCART_STORAGE_PATH:
        USER_ID:
        GROUP_ID:
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:${EXTENSION_PATH}
      - opencart:${OPENCART_PATH}
      - opencart_storage:${OPENCART_STORAGE_PATH}
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  opencart:
  opencart_storage:
